language: java
jdk: oraclejdk8
after_success: ./.travis.after_success.sh
sudo: required
dist: trusty
branches:
  only:
  - master
cache:
  directories:
  - $HOME/.m2
before_cache:
- rm -rf $HOME/.m2/repository/com/vaadin/vaadin-frontend-maven-plugin
env:
  global:
  - secure: EGBPZREMeQ2LedEF3MnMSd56nVHadPkFrAl1Z3vrDd8inc6LAaDyeXWoh8ngnJG1iuWeX0Zcd1qG2em5/4X6ahiRwmaEb5cNjb762jV+mvmyt/UXV2Ru+7YgNG9qZ0YU0NYfDD0d8FkJWzJQy6NGj2y1OQtVeuRl0UKmi0XVCRJvZrmkRTl3JnzsOMkIGQNeHs0JMJ1HkmzgOYu0DkwO5+s+htw9rKWuwpGGkRwmpicK8Igyu62aCMGSKvaeWYtRLza6hmHW4NkRVALUoe6e2IGQbcmHzv3/unIa2383REtS6tFtAGzMJnwgv+57IGBXSvb/zLljDgIC9tAFd7ceo7J2B8XHcpN0NpEveiL5iQh7UUjBUX2GpKOuRlTk/1kwIs3clLKH5X8AuzxVq2XI6R+LrdbYvRJ5BKYsoo5iXPjPMU0oX/3qoQyG85eF171Vlwu2U3uWv5nYKMBOf8aMCypBG2UqsvZzbosis5AUeGQouK2HkU7GC9SpdpuD8lu2MIWUcIKlFPFIB5FT2K919lZ2vzjvhQ3v6H7wQNqwEqwRJHSDRBFjyAeqmEKtPaFNl4KEYmf7gHSnt4nP14vGI/gkymNJpyFB6kBx+XNgY5O2ef+f/sbCr2Wm8tnnyZutbRWddveqbzQadZJWvZiLluleyeiGTBSd8FxJ5BmMTmo=
  - secure: RE26APE6/+Q7cQI9u4p1w37oEmxlOxoFQHGiQp5qftFsASeYikKa9xCKR10wj+xyAewdUWsaxpb/rPcpIhfeKa0ck6baHZdHcrhEPikNQh40yo3mZIKM+QFJzIn71+rG26Yb2ScfkatmemCYrt3QKiFAIOURxeQl8keFetbyOoJPDDvrv4bjpi67OCII6GNWVAQxMtm4nBe/6Mpu2PPIyUtO7tPFPe5IHyN1KgRTyoegSIS9XuJOLhy5aIyZmfZnmxvc4Clkr9PoO3ZT/02zGfUxWTPjW2/YZKH+RfyHwWFB/D/PZoFBuEDAPura1gH09erlHZghNQZUiNiHnXFbJqrcvC6Im5RHx8Rh7+QiHQ5G/X3nqdpIZBGDMmK9PDNEHOJpkxLluDaqy0gdWggJ5Q+AlteGW0sFWm69JZFhgS2qYyTl2Abt6R8VUaXyLr7W2ttpjHcf8idSRH7Z1nK4m1v40yThP/UyWYSiZVup8jDHZPmlgvSSYo53MUqB9mGxYnCVq8h3c3DSwVwvXtAEjvPCJvjsCY1axuh/O9YupWt5sIBGgNXzsIEMVEG9x+xIx7XGyzeOJbhj6b5y4NwGDY6upRUn6OkFJ0F6mzJ3UOa/LDtwUCPMeFyRpmSmClMErRh3SiUvmpQtUS4WP2rv+shRRC0NtXLtuvxhJngyIzw=
